=== vinicius-lier/u2000_linux/client/client/features/com.swimap.clientutiladapter/commini.dtd
<?xml version="1.0" encoding="GB2312" ?>
<!ELEMENT COMMINIDATA ( AREADESC+ ) >

<!ELEMENT AREADESC ( DESC* ) >
<!ATTLIST AREADESC areaname CDATA #IMPLIED >

<!ELEMENT DESC ( PARAS, DESC* ) >
<!ATTLIST DESC descname CDATA #IMPLIED >


<!ELEMENT PARAS ( PARA* ) >


<!ELEMENT PARA ( VALUE* ) >
<!ATTLIST PARA name CDATA #REQUIRED >
<!ATTLIST PARA type CDATA #IMPLIED >
<!ATTLIST PARA value CDATA #IMPLIED >

<!ELEMENT VALUE EMPTY >
<!ATTLIST VALUE type CDATA #IMPLIED >
<!ATTLIST VALUE value CDATA #REQUIRED >

=== vinicius-lier/u2000_linux/client/client/features/com.swimap.ftp/feature.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
	<AREADESC>
		<!--
			子系统的基本内容描述， ID 表示子系统的唯一标识,该属性是必须的 Label 该子系统的名字，该属性是必须的 IMage
			子系统图标对应的文件位置，这个是可选的
		-->
		<DESC descname="feature">
			<PARAS>
				<PARA name="id" value="com.swimap.ftp"></PARA>
				<PARA name="label" value="omc_name"></PARA>
				<PARA name="image" value="icon.gif"></PARA>
			</PARAS>
		</DESC>

		<DESC descname="extra">
			<PARAS>
				<!--由于流通的需要，这2项是必须的；用于此feature的版本和描述，和组件名称保持一致-->
				<PARA name="about.version" value="about.version" />
				<PARA name="about.desc" value="about.desc" />
			</PARAS>
		</DESC>
		<DESC descname="plugins">
			<PARAS>
				<PARA name="com.swimap.ftp"></PARA>
				<PARA name="com.swimap.ftpconf"></PARA>				
			</PARAS>
		</DESC>
		<DESC descname="required-plugins">
			<PARAS>		
			</PARAS>
		</DESC>
	</AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/features/base/feature.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
	<AREADESC>
		<!--
			子系统的基本内容描述，
			ID      表示子系统的唯一标识,该属性是必须的
			Label   该子系统的名字，该属性是必须的
			IMage   子系统图标对应的文件位置，这个是可选的
		-->
		<DESC descname="feature">
			<PARAS>
				<PARA name="id" value="base"></PARA>
				<PARA name="label" value="base"></PARA>
			</PARAS>
		</DESC>
		<!-- 子系统的其他属性描述 -->
		<DESC descname="extra">
			<PARAS>
				<!-- 加载对话框图片，用于显示在登录后的进度对话框中 -->
				<PARA name="image.loading" value=""></PARA>
				<!-- 锁定对话框图片，用于显示在客户端锁定/解锁对话框中 -->
				<PARA name="image.lock" value=""></PARA>
				<!-- 退出对话框图片，用于显示在退出确认对话框中 -->
				<PARA name="image.exit" value=""></PARA>
				<!-- 子系统版本，用于显示在关于对话框中 -->
				<PARA name="about.version" value="about.version"></PARA>
				<!-- 子系统描述，用于显示在关于对话框中 -->
				<PARA name="about.desc" value="about.desc"></PARA>
				<!-- 关于对话框图片，用于显示在关于对话框 -->
				<PARA name="about.image.banner" value=""></PARA>
				<!-- 关于对话框标题图片，用于显示在关于对话框中 -->
				<PARA name="about.image.title" value=""></PARA>
				<PARA name="about.show" value="false"/>
			</PARAS>
		</DESC>



		<DESC descname="plugins">
			<PARAS>
			  <PARA name="base"/>
			</PARAS>
		</DESC>

	</AREADESC>
</COMMINIDATA>
