=== vinicius-lier/u2000_linux/client/client/features/com.swimap.clientutiladapter/commini.dtd
<?xml version="1.0" encoding="GB2312" ?>
<!ELEMENT COMMINIDATA ( AREADESC+ ) >

<!ELEMENT AREADESC ( DESC* ) >
<!ATTLIST AREADESC areaname CDATA #IMPLIED >

<!ELEMENT DESC ( PARAS, DESC* ) >
<!ATTLIST DESC descname CDATA #IMPLIED >


<!ELEMENT PARAS ( PARA* ) >


<!ELEMENT PARA ( VALUE* ) >
<!ATTLIST PARA name CDATA #REQUIRED >
<!ATTLIST PARA type CDATA #IMPLIED >
<!ATTLIST PARA value CDATA #IMPLIED >

<!ELEMENT VALUE EMPTY >
<!ATTLIST VALUE type CDATA #IMPLIED >
<!ATTLIST VALUE value CDATA #REQUIRED >

=== vinicius-lier/u2000_linux/client/client/features/nml_vlan/feature.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
	<AREADESC>
		<!--
			子系统的基本内容描述，
			ID      表示子系统的唯一标识,该属性是必须的
			Label   该子系统的名字，该属性是必须的
			IMage   子系统图标对应的文件位置，这个是可选的
		-->
		<DESC descname="feature">
			<PARAS>
				<PARA name="id" value="nml_vlan"></PARA>
				<PARA name="label" value="nml_vlan"></PARA>
			</PARAS>
		</DESC>
		<!-- 子系统的其他属性描述 -->
		<DESC descname="extra">
			<PARAS>
				<!-- 子系统版本，用于显示在关于对话框中 -->
				<PARA name="about.version" value="about.version"></PARA>
				<!-- 子系统描述，用于显示在关于对话框中 -->
				<PARA name="about.desc" value="about.desc"></PARA>
			</PARAS>
		</DESC>
		<DESC descname="plugins">
			<PARAS>
			  <PARA name="nml_vlan"/>
			</PARAS>
		</DESC>
	</AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/platform_SecondStepStartup.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
	<AREADESC areaname="startupresources">	
		<DESC descname="startupplugins">
		<PARAS>
			</PARAS>
				<DESC descname="securityplugins">
					<PARAS>	 						
					</PARAS>
				</DESC>
				<DESC descname="requiredplugins">
					<PARAS>
						<PARA name="com.swimap.color" />
						<PARA name="com.swimap.corba" />
						<PARA name="em" />
						<PARA name="clientutilAdapter" />
						
						<PARA name="topoapp"></PARA>
						<PARA name="eam"></PARA>
						<PARA name="resource"></PARA>
						<PARA name="topoclient" />
						<PARA name="topobase" />
					</PARAS>
				</DESC>			
		</DESC>				
		
		<DESC descname="startupApplications">
			<PARAS></PARAS>
				<DESC descname="applications">
					<PARAS>
						<PARA name="AlarmMonitor"/> 
					</PARAS>
				</DESC>
		</DESC>
	</AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/u2000_SecondStepStartup.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
	<AREADESC areaname="startupresources">

		<DESC descname="startupplugins">
		<PARAS>
		</PARAS>
				<DESC descname="securityplugins">
					<PARAS>	 						
					</PARAS>
				</DESC>
				<DESC descname="requiredplugins">
					<PARAS>
					
					  <PARA name="com.swimap.adapter.message.sm"/>
					  <PARA name="com.swimap.adapter.message.common"/>
			          <PARA name="com.swimap.extension.registry"/>		
			          <PARA name="com.swimap.color"/>	

						<PARA name="alarmclient"/>
						<PARA name="com.swimap.adapter.message.fm"/>
						
						<PARA name="com.swimap.adapter.message.resource"/>
						<PARA name="com.swimap.adapter.message.tm"/>
					  <PARA name="resource"/>	
			          <PARA name="eam"/>		
			          <PARA name="topobase"/>	
					  <PARA name="topoclient"/>

					   <PARA name="unitedmgr"></PARA>

					   <PARA name="dc"></PARA>	
					   <PARA name="u2000nelicense"></PARA>	
					</PARAS>
				</DESC>			
		</DESC>				
		<DESC descname="startupLinks">
			<PARAS></PARAS>
			 <DESC descname="requiredLinks">
					<PARAS>
					    <PARA name="base"></PARA>
					    <PARA name="cbb"></PARA>
						<PARA name="unitedmgr"></PARA>
						<PARA name="im_phy"></PARA>
                        <PARA name="dc"></PARA>						
					</PARAS>
				 </DESC>
				  <DESC descname="portalLinks">
					<PARAS>
											
						
					</PARAS>
				 </DESC>
				  </DESC>
		
	</AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/applications/AlarmMonitor/nml_vlan_application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
    <AREADESC>
        <!-- 配置块中定制应用需要加载的模块和子系统信息 -->
        <DESC descname="startupElementList">
            <PARAS>
            </PARAS>
            <!-- name: plugin列表 -->
            <DESC descname="plugins">
                <PARAS>
                    <PARA name="nml_vlan"/>
                </PARAS>
            </DESC>
            <!-- name: feature列表 -->
            <DESC descname="features"/>
            <!-- name: productlib 文件夹列表 -->
            <DESC descname="productlibs">
                <PARAS>
                    <PARA name="nml_vlan"/>
                </PARAS>
            </DESC>
        </DESC>
        <DESC descname="startupcommands"> 
            <PARAS> 
                <PARA name="command" value=""/> 
                <PARA name="action" value=""/> 
                <PARA name="executable" value=""/> 
            </PARAS> 
        </DESC> 
    </AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/features/eam/feature.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
  <AREADESC>

    <DESC descname="feature">
      <PARAS>
        <PARA name="id" value="eam"></PARA>
        <PARA name="label" value="eam_name"></PARA>
        <PARA name="image" value="icon.gif"></PARA>       
      </PARAS>
    </DESC>
    
		<DESC descname="extra">
			<PARAS>
				<PARA name="image.loading" value="loading.png"></PARA>
				<PARA name="image.lock" value="lockdialog.gif"></PARA>
				<PARA name="image.exit" value="logoutdialog.gif"></PARA>
				<PARA name="about.version" value="about.version"></PARA>
				<PARA name="about.desc" value="about.desc"></PARA>
				<PARA name="about.image.banner"
					value="about_banner.gif">
				</PARA>
				<PARA name="about.image.title"
					value="about_title.png">
				</PARA>
			</PARAS>
		</DESC>
    
    <DESC descname="plugins">
        <PARAS>
             <PARA name="com.swimap.rpc"></PARA>
             <PARA name="com.swimap.orbbase"></PARA>
             <PARA name="eam"> </PARA>
		         <PARA name="authentication"></PARA>
		         <PARA name="loginui"></PARA>	
		         <PARA name="clientutil"></PARA>
        </PARAS>
    </DESC>
    <DESC descname="required-plugins">
      <PARAS>        
      <PARA name="com.swimap.extension.registry"></PARA>
      <PARA name="resource"> </PARA> 
     </PARAS>
    </DESC>
  </AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/features/com.swimap.adapter.message.resource/feature.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
  <AREADESC>
    <DESC descname="feature">
      <PARAS>
        <PARA name="id" value="com.swimap.adapter.message.resource"></PARA>
        <PARA name="label" value="com.swimap.adapter.message.resource"></PARA>
        <PARA name="image" value="icon.gif"></PARA>       
      </PARAS>
    </DESC>
    
		<DESC descname="extra">
			<PARAS>
				<PARA name="image.loading" value="loading.gif"></PARA>
				<PARA name="image.lock" value="lockdialog.gif"></PARA>
				<PARA name="image.exit" value="logoutdialog.gif"></PARA>
				<PARA name="about.version" value="about.version"></PARA>
				<PARA name="about.desc" value="about.desc"></PARA>
				<PARA name="about.image.banner"
					value="about_banner.gif">
				</PARA>
				<PARA name="about.image.title"
					value="about_title.png">
				</PARA>
				<PARA name="about.show" value="false"/>
			</PARAS>
		</DESC>
    
    <DESC descname="plugins">
      <PARAS>
        <PARA name="com.swimap.adapter.message.resource"> </PARA>
     </PARAS>
    </DESC>
   
    <DESC descname="required-plugins">
      <PARAS>
      <PARA name="com.swimap.extension.registry"></PARA>
      <PARA name="com.swimap.adapter.message.common"> </PARA>
      <PARA name="com.swimap.adapter.message.general"> </PARA>
     </PARAS>
    </DESC>
  </AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/features/alarmclientgui/feature.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
    <AREADESC>
        <!--
            Description:the plugin despration
            ID      the ID of the plugin ,it must set
            Label   the Name of the plugin,it must set
            IMage   the plugin image path ,it can select
        -->
        <DESC descname="feature">
            <PARAS>
                <PARA name="id" value="alarmclientgui"/>
                <PARA name="label" value="alarmclient_name"/>
                <PARA name="image" value="icon.gif"/>
            </PARAS>
        </DESC>
        <!--
            Description: the plugin other despration
        -->
        <DESC descname="extra">
            <PARAS>
                <!-- loading pic,it shows in loading dialog-->
                <PARA name="image.loading" value="loading.png"/>
                <!-- lock pic ,it shows in lock/unlock dialog-->
                <PARA name="image.lock" value="lockdialog.gif"/>
                <!-- exit pic,it shows at confirm dialog of exit-->
                <PARA name="image.exit" value="logoutdialog.gif"/>
                <!--the plugin version,it shows at about dialog-->
                <PARA name="about.version" value="about.version"/>
                <!-- the plugin description,it shows at about dialog-->
                <PARA name="about.desc" value="about.desc"/>
                <!-- the about pic,it shows at about dialog-->
                <PARA name="about.image.banner" value="about_banner.gif"/>
                <!-- the title pic of about dialog-->
                <PARA name="about.image.title" value="about_title.png"/>
            </PARAS>
        </DESC>
        <DESC descname="plugins">
            <PARAS>
                <PARA name="alarmclientbase"/>
                <PARA name="alarmclient"/>
                <PARA name="alarmclientgui"/>
                <PARA name="alarmclientextgui"/>
                <PARA name="alarmclienttool"/>
	        <PARA name="querydumptool"/>
                <PARA name="authentication"/>
                <PARA name="loginui"/>
                <PARA name="clientutil"/>
                <PARA name="com.swimap.rpc"/>
                <PARA name="WelcomePage"/>
            </PARAS>
        </DESC>
        <!--
            Description:the plugin loading depends on plugins 
            name=""the plugin name ,it must set
        -->
        <DESC descname="required-plugins">
            <PARAS>
                <PARA name="com.swimap.color"/>
                <PARA name="com.swimap.sound"/>
                <PARA name="com.swimap.extension.registry"/>
                <PARA name="com.swimap.orbbase"/>
                <PARA name="eam"/>
                <PARA name="resource"/>
                <PARA name="lm"/>
            </PARAS>
        </DESC>
    </AREADESC>
</COMMINIDATA>

=== vinicius-lier/u2000_linux/client/client/style/productstyle/conf/mainfrm/debugtracerfileconf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMMINIDATA SYSTEM "commini.dtd">
<COMMINIDATA>
<AREADESC>
<!-- configuration information for debugtrace files  -->
<DESC descname="debugTracerFileDelete">
    <PARAS>   
    <!-- specifies debugtracer files should be removed or not, default false -->
    <PARA name="isDTFileToBeRemoved" value="false"></PARA>
    <!-- max size in MB, if folder size exceeds this limit debugtracer files will be removed, default value is 500-->
    <PARA name="maxSize" value="500"></PARA>
    <!-- total number of debugtracer files to be removed, default value is 20-->
    <PARA name="totalNoOfFileToRemove" value="20"></PARA>  
       
    <!-- Configure the information to create the zip file  
         The zipping will be done when the below parameters 
         will be valid and the parameters will be uncommented
         The value of the totalNoOfFileToZip parameter should be 
         positive integer value
         The value of the maxNoOfZipFiles parameter should be 
         positive integer value
         The value of the totalNoOfZipFileToRemove parameter should be 0
         or positive integer value 
    -->
    
    <!--specifies number of debugtracer files should be zipped -->
    <PARA name="totalNoOfFileToZip" value="20"></PARA>
    <!--specifies maximum number of zip files should be in the folder -->
    <PARA name="maxNoOfZipFiles" value="30"></PARA>
    <!--specifies maximum number of zip files should be removed from the folder -->
    <PARA name="totalNoOfZipFileToRemove" value="1"></PARA>
       
  </PARAS>   
  </DESC> 
</AREADESC>
</COMMINIDATA>
