=== vinicius-lier/u2000_linux/client/client/plugins/securitymanager/style/conf/dtd/popupmenu.dtd
<?xml version="1.0" encoding="GB2312" ?>

<!ELEMENT popupMenu ( menu*) >

<!ELEMENT menu ( name , nodeType*, menuItem* , separator* ) >

<!ELEMENT separator (operator? , (previous-item | next-item)? )>

<!ELEMENT menuItem ( name, operator? , (previous-item | next-item)? , mnemonic?, methodName, objectClassName?, accessID? ,extraType?) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT nodeType ( #PCDATA ) >

<!ELEMENT mnemonic ( #PCDATA ) >

<!ELEMENT methodName ( #PCDATA ) >

<!ELEMENT objectClassName ( #PCDATA ) >

<!ELEMENT accessID ( #PCDATA ) >

<!ELEMENT extraType ( #PCDATA ) >

<!ELEMENT operator ( #PCDATA ) >

<!ELEMENT previous-item ( #PCDATA ) >

<!ELEMENT next-item ( #PCDATA ) >

=== vinicius-lier/u2000_linux/client/client/plugins/securitymanager/style/conf/popupmenu.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE popupmenu SYSTEM "dtd/popupmenu.dtd">
<popupMenu>
    <menu>
        <name>Root</name>
        <nodeType>0</nodeType>
        <!--
        <menuItem>
            <name>refresh</name>
            <mnemonic>R</mnemonic>
            <methodName>refresh</methodName>
        </menuItem>
        <menuItem>
            <name>rightsGranted_menu</name>
            <mnemonic>A</mnemonic>
            <methodName>QueryRightsGranted</methodName>
        </menuItem>
        -->
    </menu>

    <menu>
        <name>NEUserRoot</name>
        <nodeType>6</nodeType>
        <!--menuItem>
            <name>filterTreeByNEType</name>
            <mnemonic>N</mnemonic>
            <methodName>filterTreeByNEType</methodName>
        </menuItem>
        <menuItem>
            <name>showAllNEType</name>
            <mnemonic>O</mnemonic>
            <methodName>showAllNEType</methodName>
        </menuItem-->
    </menu>

    <menu>
        <name>NEUser_NENode</name>
        <nodeType>7</nodeType>
        <menuItem>
            <name>createNEUser</name>
            <mnemonic>N</mnemonic>
            <methodName>createNEUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>NEUser_Create_Delete_Modify</accessID>
        </menuItem>
    </menu>

    <menu>
        <name>NEUser</name>
        <nodeType>8</nodeType>
        <menuItem>
            <name>deleteNEUser</name>
            <mnemonic>L</mnemonic>
            <methodName>deleteNEUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>NEUser_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>changeNEUserPassword</name>
            <mnemonic>P</mnemonic>
            <methodName>changeNEUserPassword</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>Change_NEUser_Password</accessID>
        </menuItem>
    </menu>

    <menu>
        <name>Users</name>
        <nodeType>11</nodeType>
        <menuItem>
            <name>createUser</name>
            <mnemonic>N</mnemonic>
            <methodName>createUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
    </menu>

    <menu>
        <name>User</name>
        <nodeType>12</nodeType>
        <menuItem>
            <name>applySaveUser</name>
            <mnemonic>A</mnemonic>
            <methodName>applySaveUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <extraType>1</extraType>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>resetPassword</name>
            <mnemonic>E</mnemonic>
            <methodName>resetPassword</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>Reset_Password</accessID>
        </menuItem>
        <menuItem>
            <name>deleteUser</name>
            <mnemonic>L</mnemonic>
            <methodName>deleteUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>unlockUser</name>
            <mnemonic>U</mnemonic>
            <methodName>unlockUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>Unlock_User</accessID>
        </menuItem>
	<menuItem>
            <name>enableAccount</name>
            <mnemonic>O</mnemonic>
            <methodName>enableAccount</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>moveObj2Region</name>
            <mnemonic>V</mnemonic>
            <methodName>moveObj2Region</methodName>
        </menuItem>
    </menu>
    <menu>
        <name>UserInRegion</name>
        <nodeType>20</nodeType>
        <menuItem>
            <name>applySaveUser</name>
            <mnemonic>A</mnemonic>
            <methodName>applySaveUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <extraType>1</extraType>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>resetPassword</name>
            <mnemonic>E</mnemonic>
            <methodName>resetPassword</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>Reset_Password</accessID>
        </menuItem>
        <menuItem>
            <name>deleteUser</name>
            <mnemonic>L</mnemonic>
            <methodName>deleteUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>unlockUser</name>
            <mnemonic>U</mnemonic>
            <methodName>unlockUser</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>Unlock_User</accessID>
        </menuItem>
    <menuItem>
            <name>enableAccount</name>
            <mnemonic>O</mnemonic>
            <methodName>enableAccount</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>moveObj2Region</name>
            <mnemonic>V</mnemonic>
            <methodName>moveObj2Region</methodName>
        </menuItem>
    </menu>
    <menu>
        <name>UserGroups</name>
        <nodeType>13</nodeType>
        <menuItem>
            <name>createUserGroup</name>
            <mnemonic>N</mnemonic>
            <methodName>createUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>createPSAGroup</name>
            <mnemonic>P</mnemonic>
            <methodName>createPSAGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>synUserGroup</name>
            <mnemonic>S</mnemonic>
            <methodName>synUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
    </menu>
    <menu>
        <name>UserGroup</name>
        <nodeType>14</nodeType>
        <menuItem>
            <name>deleteUserGroup</name>
            <mnemonic>L</mnemonic>
            <methodName>deleteUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>moveObj2Region</name>
            <mnemonic>V</mnemonic>
            <methodName>moveObj2Region</methodName>
        </menuItem>
    </menu>
    <menu>
        <name>PSAGroup</name>
        <nodeType>15</nodeType>
        <menuItem>
            <name>deleteUserGroup</name>
            <mnemonic>L</mnemonic>
            <methodName>deleteUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>moveObj2Region</name>
            <mnemonic>V</mnemonic>
            <methodName>moveObj2Region</methodName>
        </menuItem>
    </menu>
    <menu>
        <name>UserGroups_Menu</name>
        <menuItem>
            <name>createUserGroup</name>
            <mnemonic>N</mnemonic>
            <methodName>createUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>createPSAGroup</name>
            <mnemonic>P</mnemonic>
            <methodName>createPSAGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>synUserGroup</name>
            <mnemonic>S</mnemonic>
            <methodName>synUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>deleteUserGroup</name>
            <mnemonic>L</mnemonic>
            <methodName>deleteUserGroup</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>UserGroup_Create_Delete_Modify</accessID>
        </menuItem>
        <menuItem>
            <name>moveObj2Region</name>
            <mnemonic>V</mnemonic>
            <methodName>moveObj2Region</methodName>
        </menuItem>
        <separator>
        </separator>
        <menuItem>
            <name>refresh</name>
            <mnemonic>R</mnemonic>
            <methodName>userRefresh</methodName>
            <objectClassName>SecurityApplication</objectClassName>
            <accessID>User_Create_Delete_Modify</accessID>
        </menuItem>
        <separator>
        </separator>
        <menuItem>
            <name>printData</name>
            <mnemonic>P</mnemonic>
            <methodName>printData</methodName>
            <extraType>0</extraType>
        </menuItem>
        <menuItem>
            <name>saveData</name>
            <mnemonic>A</mnemonic>
            <methodName>saveData</methodName>
            <extraType>0</extraType>
        </menuItem>
